tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "asdf"
brew "awscli"
brew "node"
brew "corepack"
brew "curl"
brew "fish"
brew "fzf"
brew "ghq"
brew "git"
brew "go"
brew "imagemagick"
brew "mas"
brew "tmux"
brew "tree"
brew "vim"
cask "1password"
cask "altair-graphql-client"
cask "aquaskk"
cask "bettertouchtool"
cask "brewlet"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "insomnia"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "mimestream"
cask "notion"
cask "postico"
cask "qblocker"
cask "scroll-reverser"
cask "sequel-ace"
cask "slack"
cask "stats"
cask "toggl-track"
cask "visual-studio-code"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Grammarly for Safari", id: 1462114288
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "OctoLinker", id: 1549308269
mas "Pages", id: 409201541
